spring:
  application:
    name: provider
server:
  port: 9090

#指定当前应用/服务名字，相同的服务应同名
dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181 #注册地址
  provider:
    timeout: 3000

#自定义属性，用来规定dubbo服务的版本号
demo:
  service:
    version: 1.0.0

